language: cpp
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository ppa:zink-chimaera/cmake -y
    - sudo apt-get update -q
    - sudo apt-get install cmake -y
    - ./ci/install_dependencies.sh

script:
    - ./ci/build_and_run_tests.sh
